### ISSUE TITLE
Unnecessary focusing triggers incorrect display on "No more subgoals".

### ISSUE THREAD

**Issue by Zimmi48** [EugeneLoy/coq_jupyter#42]
Example:

```
Lemma foo : True /\ False.
Proof.
split.
- idtac.
  {
    idtac.
    easy.
  }
- idtac.
```

prints "No more subgoals" even though an (unfocused) subgoal actually remains.

(with coq_jupyter 1.5.1 and Coq 8.11.0)

**Comment by EugeneLoy** [comment]
Fixed by #41.

**Comment by Zimmi48** [comment]
Did you mean "fixed by 80834cfb48197719f2a150bc1498748b92e69ffd"?

**Comment by EugeneLoy** [comment]
No, in terms of commits ced668377890c6a4ff6f98854fea1ecbac517b7c fixes this.

The problem was not in extra focusing per se, rather in the fact that non-dot separators was not handled properly.

Part of your code, after `}` (whole line `- idtac.`) was not handed to coq properly (fixed by #41), so focusing on next goal never happened. This was compounded by issue related to displaying background goals in absence of unresolved foreground ones (fixed by #40), hence you received "No more subgoals"  message.

**Comment by EugeneLoy** [comment]
In any case, I've updated [binder demo](https://mybinder.org/v2/gh/EugeneLoy/coq_jupyter_demo/master?filepath=demo.ipynb) so you can verify that it works as intended now.

**Comment by Zimmi48** [comment]
Ah I see! An interaction of two previously reported bugs :laughing: 
Yes, I've already updated my students' project to 1.5.3 and did test that the issues were gone. Thanks again!
